### ISSUE TITLE
New Feature: Returning total run time

### ISSUE THREAD

**Issue by tomatobrown** [jody-zeitler/cuke-skywalker#1]
A cool feature to add would be a way to print out the runtime per thread as well as the total runtime of the execution

**Comment by jody-zeitler** [comment]
Thread runtime is already captured, at least for Cucumber 3:

```
4 scenarios (4 passed)
35 steps (35 passed)
0m46.721s
```

The roundrobin distribution doesn't use long-running threads -- it creates them as needed -- so thread runtime isn't quite the same as it is for the uniform distribution method.

I think total runtime would better be captured with an external wrapper.
